### ISSUE TITLE
Ask about the input file or data format

### ISSUE THREAD

**Issue by newera912** [manavs19/subgraph-outlier-detection#1]
Hi,
Can you provide us the input file format for your code or sample input files. I searched the links "http://dais.cs.uiuc.edu/manish/LocalLearningOutlier/." you provide in your paper, the link is invalid right now. it very nice of if help me to this favor.  thank you.

**Comment by manavs19** [comment]
Hi,

I don't think the earlier mail got sent. Github's mail server is not
allowing me to send the files due to their size. I can send you the files
directly if you can give me your email address.

Regards,
Manav

**Comment by newera912** [comment]
Thank you for your reply. My email address: alex-912 \at live \dot cn  or    aalimu \at albany \dot edu.
Thank you, it will very helpful if you send me the files. 
If the files big github or google driver will be work.

**Comment by newera912** [comment]
My e-mail is : alex-912@live.cn .  Can you send the data and code. it will be very helpful.
